name: Deploy

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Install SSH agent and add key
        run: |
          sudo apt-get update && sudo apt-get install -y expect
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          expect -c "
            spawn ssh-add ~/.ssh/id_rsa
            expect \"Enter passphrase for /home/runner/.ssh/id_rsa:\"
            send \"${{ secrets.PASSPHRASE }}\r\"
            expect eof
          "
          ssh-add -l  # Lists the SSH keys to confirm addition


      - name: Test SSH connection
        run: ssh -Tvvv git@github.com

 







